### ISSUE TITLE
Is it possible to prevent modal responsive resize?

### ISSUE THREAD

**Issue by ahmedtabrez** [MeteorStuff/meteor-materialize-modal#10]
<img src="https://cloud.githubusercontent.com/assets/5443412/11997454/e55538b8-aaa1-11e5-979b-f43565a91800.jpg" width="300">
### Looks nice

But when an input field gains focus: 

<img src="https://cloud.githubusercontent.com/assets/5443412/11997459/2c8c83b2-aaa2-11e5-9cd7-c6f471751527.jpg" width="300">
### This is not bad but a little awkward.

The situation is worse on small screens especially when `fixedFooter:true`. 
The modal becomes so small that it becomes very difficult to scroll and touch on the next input.
Any thoughts on how to handle this?

**Comment by msolters** [comment]
Unfortunately this is a problem with Android itself - whenever the keyboard is shown or hidden it effectively resizes the `window`, so CSS will obey the changes just as if you'd manually resized a browser window.

I'm not sure how it would be possible to override this without setting a naiive `min-height` value and hope it works for _most_ devices. Of course it won't hold for devices in landscape...

But the problem is really in the way the device handles the window dimensions.  The CSS trickery required to override this demands some assumptions.

**Comment by ahmedtabrez** [comment]
@msolters, Just a crude suggestion:

Can we listen to the focus event on the input fields, take note of the height (initial height) and dynamically set the `min-height` to the initial height ?

## Further:

[How do I Detect if Software Keyboard is Visible on Android Device?](http://stackoverflow.com/questions/4745988/how-do-i-detect-if-software-keyboard-is-visible-on-android-device)

[How to capture the 'virtual keyboard show/hide' event in Android?](http://stackoverflow.com/questions/4312319/howto-capture-the-virtual-keyboard-show-hide-event-in-android)

**Comment by msolters** [comment]
Sure! The problem is that may not be appropriate or helpful default behaviour. It may produce problems for some peoples modals.  It seems to me that it should be either
-  optional by argument (i.e. `{ignoreSoftkeys: true}` or similar)
-  implemented by the end user (i.e. not included in the package)

@pfafman is trying to be a little more conservative with the complexity of this package so I think we should defer to his opinion on whether or not we should add in this kind of logic.

**Comment by pfafman** [comment]
This is a CSS issue and all the CSS except for the fullscreen modal is handled in [Materializecss](http://materializecss.com).  What you are demonstrating would happen even if you were not using this package and using a modal generated directly with Materialzecss.

Your options are to 
- open an issue with them to fix this somehow in their framework.
- do something on the enduser side where you as stated dynamically set the min-height.  Although in my experience this leads to other UI issues with the keyboard.
- Move to a full screen modal on mobile devices. Which is what I do in my applications.  The keyboard is still a UI mess but less so.

But this is not something I want to fix in this package.  I am trying to keep it as close to what in in Materialzecss as possible and only expose the options that they have in their [model](http://materializecss.com/modals.html).
