### ISSUE TITLE
Page is a little wider than window when use fullscreen with fixedFooter.

### ISSUE THREAD

**Issue by zhaoyao91** [MeteorStuff/meteor-materialize-modal#12]
When I use fullscreen with fixedFooter:

```
    MaterializeModal.display({
        bodyTemplate: "AccountModal",
        closeLabel: "返回",
        fullscreen: true,
        fixedFooter: true,
        inDuration: 300,
        outDuration: 300
    })
```

there is a horizontal scroll in both pc and mobile, which is bad in mobile:

![qq 20160108230647](https://cloud.githubusercontent.com/assets/3808838/12200954/85e22a96-b65c-11e5-9a62-9783effc7ab5.png)

**Comment by msolters** [comment]
Well, let's find out if it's due to the package itself.  Can you go to the [demo site](http://materializemodal.meteor.com/) and execute the following code in the developer tools console?

``` js
MaterializeModal.confirm({
  bodyTemplate: "loremIpsum",
  fixedFooter: true,
  fullscreen: true
});
```

Does that produce horizontal scrolling, and if so, what browser/OS?

In Ubuntu Chrome, there are no problems.  If it looks fine on your end too, then the problem is caused by something specific to your site there.  But let's narrow it down first.  Does the demo page reproduce this issue?

**Comment by zhaoyao91** [comment]
No, it didn't occur on demo page.
But by comparing the two pages, I found out what lead to my problem:

on my page:
![qq 20160108234959](https://cloud.githubusercontent.com/assets/3808838/12202039/8c7953ce-b662-11e5-854b-65d194fe7bab.png)

on demo page:
![qq 20160108235034](https://cloud.githubusercontent.com/assets/3808838/12202053/a306ee58-b662-11e5-847d-6dde36f31ca7.png)

But I don't konw what lead to this load order difference.

**Comment by msolters** [comment]
That is interesting.  Nice sleuthing.  Correct me if I'm wrong but that
.modal.modal-fixed-footer definition is coming from Materialize?

**Comment by zhaoyao91** [comment]
yes, .modal.modal-fixed-footer definition is coming from Materialize. 

load-order does matter, but you can't specify effect by controlling it.

I have created a PR, it works for me, please review if it fix this case. (or, specify the effect as you wish)
