### ISSUE TITLE
dismissable material option

### ISSUE THREAD

**Issue by palpinter** [MeteorStuff/meteor-materialize-modal#3]
Hi,

is there any way to use 'dismissable' option?

I've tried:

```
  $('#materializeModal').leanModal({
    dismissible: false
    });
```

but doesn't work.

Thx
Pal

**Comment by msolters** [comment]
This is doable.  I wouldn't expect that method to work since, when modals are closed, their nodes are removed from the DOM -- when they are open, it will produce collisions.

---

In the meantime (before I push a PR that applies the `dismissible` option), you may find something useful in another Material modal package, [Modalize](http://modalize.meteor.com/).  It is a fork of this package; it is simpler, but much more powerful.  Indeed, `dismissible` is an option I built into it from the start (http://modalize.meteor.com/#dismiss-behaviour), and I also provide `dismissed` events which can be detected from the bodyTemplate.
