### ISSUE TITLE
hooking to the close modal event? 

### ISSUE THREAD

**Issue by shmuel-web** [MeteorStuff/meteor-materialize-modal#9]
this is more of a question then an issue

i am trying to do some animations when the modal closes but 
i cant use the callback because its invoked after the modal is fully closed
is there a close event i can hook to when the modal starts closing?

thanks

**Comment by msolters** [comment]
Hi @shmuel-web, the callback is invoked inside the `complete` function that is passed to the modal when created (https://github.com/MeteorStuff/meteor-materialize-modal/blob/master/lib/modal.coffee#L75), and the `complete` function is itself a callback for the `openModal` method which comes from Materialize itself.

Unfortunately, that means there is no convenient way to hook into the closing of the modal until it has already been destroyed.

There is an important distinction that you must consider, which is that a modal can be closed due to 2 separate cases:
-  Use dismisses it (clicks on background instead of hitting confirm or cancel)
-  User completes action (i.e. save form or send message or whatever the purpose of your modal is)

Therefore, due to the reliance of Materialize's `openModal` callbacks, you'll have to add your own logic in two separate places in order to catch all possible modal closures.

This is a structural problem I myself ran into with this package, and was the motivation behind the "custom dismiss" feature I built into my own package, Modalize; see here:  http://modalize.meteor.com/#dismiss-behaviour

**Comment by shmuel-web** [comment]
thanks!
